#!/usr/bin/env python3

for line in open('stack.yaml'):
    parts = line.split()
    if not parts: 
        continue
    if not parts[0] == 'resolver:':
        continue
    print(parts[1])
    break
