flags: {}
extra-deps:
  - streaming-wai-0.1.1
  - aeson-1.1.2.0
  - attoparsec-0.13.1.0
  - streaming-0.1.4.5
  - streaming-bytestring-0.1.4.6
  - streaming-commons-0.1.17
  - mmorph-1.0.9
  - streaming-utils-0.1.4.7
resolver: lts-10.9
